#!/usr/bin/env python3
"""Stage 4 of ig-opinion-radar: POST the rollup to an n8n webhook for email delivery.

Reads {pipeline_dir}/author_rollup.csv + {pipeline_dir}/classified.jsonl,
renders an HTML + markdown summary, base64s the CSV, and POSTs JSON to the
webhook URL (env IG_OPINION_RADAR_WEBHOOK, or ~/.ig-opinion-radar-webhook).

The n8n side decodes the attachment and fires Gmail. See SKILL.md
"Stage 4 - Email delivery" for the n8n workflow shape.

Usage:
    python3 send_email.py \
      --pipeline-dir ig-opinion-pipeline-running-therapy \
      --opinion "bieganie to terapia" \
      --to you@example.com \
      --cc team@example.com \
      --bcc archive@example.com \
      --token "<X-Radar-Token>"

Token resolution order: --token flag → env IG_OPINION_RADAR_TOKEN →
~/.ig-opinion-radar-token. Webhook URL resolution: env
IG_OPINION_RADAR_WEBHOOK → ~/.ig-opinion-radar-webhook.

Exits 0 on success, non-zero on any failure with the error on stderr.
"""
import argparse
import base64
import csv
import datetime as dt
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

DEFAULT_TO = "you@example.com"


def webhook_url() -> str:
    url = os.environ.get("IG_OPINION_RADAR_WEBHOOK", "").strip()
    if url:
        return url
    fallback = Path.home() / ".ig-opinion-radar-webhook"
    if fallback.exists():
        return fallback.read_text().strip()
    sys.exit(
        "no webhook URL found. set IG_OPINION_RADAR_WEBHOOK env var or "
        "write the URL to ~/.ig-opinion-radar-webhook"
    )


def webhook_token(cli_token: str | None) -> str:
    if cli_token:
        return cli_token.strip()
    env = os.environ.get("IG_OPINION_RADAR_TOKEN", "").strip()
    if env:
        return env
    fallback = Path.home() / ".ig-opinion-radar-token"
    if fallback.exists():
        return fallback.read_text().strip()
    sys.exit(
        "no webhook token found. pass --token, set IG_OPINION_RADAR_TOKEN env "
        "var, or write the token to ~/.ig-opinion-radar-token"
    )


def slug(text: str) -> str:
    safe = "".join(c if c.isalnum() else "-" for c in text.lower())
    return "-".join(p for p in safe.split("-") if p)[:50]


def truncate(text: str, n: int) -> str:
    return text if len(text) <= n else text[: n - 1] + "…"


def load_rollup(csv_path: Path):
    with csv_path.open() as f:
        return list(csv.DictReader(f))


def tier(row) -> str:
    score = float(row.get("score", 0))
    if score >= 0.80:
        return "tier1"
    if score >= 0.20:
        return "tier2"
    return "tier3"


def render_html(opinion: str, rows: list, window: tuple, corpus_size: int) -> str:
    by_tier = {"tier1": [], "tier2": [], "tier3": []}
    for r in rows:
        by_tier[tier(r)].append(r)

    def row_to_tr(r):
        username = r["username"]
        return (
            f"<tr>"
            f"<td>{r['rank']}</td>"
            f'<td><a href="{r["profile_url"]}">@{username}</a></td>'
            f"<td>{r['fullName']}</td>"
            f"<td><b>{r['score']}</b></td>"
            f'<td><i>"{r["top_quote"]}"</i></td>'
            f'<td><a href="{r["top_url"]}">post</a></td>'
            f"</tr>"
        )

    def section(title, items, empty_msg):
        if not items:
            return f"<h3>{title}</h3><p><i>{empty_msg}</i></p>"
        rows_html = "\n".join(row_to_tr(r) for r in items)
        return (
            f"<h3>{title} ({len(items)})</h3>"
            "<table border=1 cellpadding=6 cellspacing=0 style='border-collapse:collapse'>"
            "<tr><th>#</th><th>Profile</th><th>Name</th><th>Score</th><th>Evidence</th><th>Post</th></tr>"
            f"{rows_html}</table>"
        )

    return f"""<!doctype html><html><body style="font-family:-apple-system,sans-serif;max-width:800px">
<h2>IG Opinion Radar</h2>
<p><b>Opinion scanned:</b> <i>"{opinion}"</i></p>
<p><b>Window:</b> {window[0]} - {window[1]} (~5 weeks)<br>
<b>Corpus:</b> {corpus_size} posts classified - <b>{len(rows)}</b> unique authors</p>

{section("Tier 1 - holds this opinion (score >= 0.80)", by_tier["tier1"],
         "No authors clearly endorse this opinion in the last 5 weeks. Try a broader query or a longer window.")}

{section("Tier 2 - adjacent (0.20-0.79)", by_tier["tier2"],
         "No adjacent matches.")}

{section("Tier 3 - different framing or unrelated", by_tier["tier3"],
         "All authors held the opinion to some degree.")}

<hr><p style="color:#888;font-size:12px">
Generated by ig-opinion-radar skill. Full artefacts:
posts.jsonl + classified.jsonl + author_rollup.csv attached.
Methodology: xpoz lexical harvest -> in-session semantic classification -> author rollup.
</p></body></html>"""


def render_markdown(opinion: str, rows: list, window: tuple, corpus_size: int) -> str:
    lines = [
        "# IG Opinion Radar",
        "",
        f"**Opinion scanned:** *{opinion}*  ",
        f"**Window:** {window[0]} → {window[1]} (~5 weeks)  ",
        f"**Corpus:** {corpus_size} posts → **{len(rows)}** unique authors",
        "",
    ]
    by_tier = {"tier1": [], "tier2": [], "tier3": []}
    for r in rows:
        by_tier[tier(r)].append(r)

    for label, items, empty in [
        ("Tier 1 — holds this opinion (score ≥ 0.80)", by_tier["tier1"], "_No strong matches._"),
        ("Tier 2 — adjacent (0.20–0.79)", by_tier["tier2"], "_No adjacent matches._"),
        ("Tier 3 — different framing or unrelated", by_tier["tier3"], "_All authors aligned._"),
    ]:
        lines.append(f"## {label}")
        if not items:
            lines.append(empty)
        else:
            lines.append("| # | Profile | Name | Score | Evidence | Post |")
            lines.append("|---|---|---|---|---|---|")
            for r in items:
                lines.append(
                    f"| {r['rank']} | [@{r['username']}]({r['profile_url']}) | "
                    f"{r['fullName']} | **{r['score']}** | "
                    f"\"{r['top_quote']}\" | [post]({r['top_url']}) |"
                )
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pipeline-dir", required=True, type=Path)
    ap.add_argument("--opinion", required=True)
    ap.add_argument("--to", default=DEFAULT_TO)
    ap.add_argument("--cc", action="append", default=[],
                    help="CC recipient (repeatable)")
    ap.add_argument("--bcc", action="append", default=[],
                    help="BCC recipient (repeatable)")
    ap.add_argument("--token", default=None,
                    help="webhook X-Radar-Token (else env IG_OPINION_RADAR_TOKEN "
                         "or ~/.ig-opinion-radar-token)")
    args = ap.parse_args()

    csv_path = args.pipeline_dir / "author_rollup.csv"
    if not csv_path.exists():
        sys.exit(f"missing {csv_path} - run Stage 3 (rollup.py) first")

    rows = load_rollup(csv_path)
    if not rows:
        sys.exit(f"{csv_path} is empty")

    # date window: today minus 5 weeks → today
    today = dt.date.today()
    window = ((today - dt.timedelta(days=35)).isoformat(), today.isoformat())
    corpus_size = sum(int(r.get("yes", 0)) + int(r.get("partial", 0))
                      + int(r.get("no", 0)) + int(r.get("unrelated", 0)) for r in rows)

    html = render_html(args.opinion, rows, window, corpus_size)
    md = render_markdown(args.opinion, rows, window, corpus_size)

    # write local copies too, for inspection
    (args.pipeline_dir / "email_summary.html").write_text(html)
    (args.pipeline_dir / "email_summary.md").write_text(md)

    csv_bytes = csv_path.read_bytes()
    csv_b64 = base64.b64encode(csv_bytes).decode()

    tier1_count = sum(1 for r in rows if tier(r) == "tier1")
    tier2_count = sum(1 for r in rows if tier(r) == "tier2")

    payload = {
        "opinion": args.opinion,
        "to": args.to,
        "subject": f"IG Opinion Radar: {truncate(args.opinion, 60)} - {tier1_count} Tier-1 authors",
        "summary": {
            "tier1_count": tier1_count,
            "tier2_count": tier2_count,
            "total_authors": len(rows),
            "corpus_size": corpus_size,
            "date_window": f"{window[0]} to {window[1]}",
        },
        "html_body": html,
        "markdown_body": md,
        "csv_attachment_b64": csv_b64,
        "csv_filename": f"ig-opinion-radar-{slug(args.opinion)}-{today.isoformat()}.csv",
        "run_artefacts_path": str(args.pipeline_dir.resolve()),
    }
    if args.cc:
        payload["cc"] = args.cc
    if args.bcc:
        payload["bcc"] = args.bcc

    url = webhook_url()
    token = webhook_token(args.token)
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode(),
        headers={
            "Content-Type": "application/json",
            "X-Radar-Token": token,
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            body = r.read().decode()
            print(f"OK ({r.status}) -> {args.to}", file=sys.stderr)
            print(body)
    except urllib.error.HTTPError as e:
        sys.exit(f"webhook returned {e.code}: {e.read().decode()}")
    except urllib.error.URLError as e:
        sys.exit(f"webhook unreachable: {e.reason}")


if __name__ == "__main__":
    main()
